FROM java:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/microserv-test-0.0.1-SNAPSHOT-standalone.jar /microserv-test/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/microserv-test/app.jar"]
